version: 0.1.0

llms:
  openai-gpt3.5:
    type: openai
    params:
      openai_api_key: ""
      model: "gpt-3.5-turbo"
      max_tokens: 4096

  openai-gpt3.5-16k:
    type: openai
    params:
      openai_api_key: ""
      model: "gpt-3.5-turbo-16k"
      max_tokens: 16384
  
  openai-gpt4:
    type: openai
    params:
      openai_api_key: ""
      model: "gpt-4"
      max_tokens: 4096

  llama-cpp-server:
    type: llama
    params:
      llama_cpp_server_url: "http://localhost:8000"
      api_version: "v1"
      max_tokens: 4096

indexers:
  summary:
    index_name: "summary"
    type: "summary"
    params:
      llm: "openai-gpt3.5-16k"
      llm_coroutines: 5
  chunks: 
    index_name: "chunk"
    type: "chunk"
    params:

dataloaders:
  primary:
    type: notion
    indexers:
      - summary
      - chunks
    config:
      max_tokens: 1024
      notion_token: 
      database_id: 
      title_prop: "Title"
      last_edited_prop: "Last edited time"
      metadata:
        - key: "source"
          display: "Source"
          property_name: ""
        - key: "date"
          display: "Date of writing"
          property_name: ""









